apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.14.4
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: test-external-secrets
